version: '2'
services:
  nginx:
    restart: always
    build: ./nginx
    logging:
        driver: "json-file"
        options: 
            max-size: "10m"
            max-file: "10"
    ports:
     - "80:80"
    links:
     - mapproxy:mapproxy
  mapproxy:
    restart: always
    build: ./mapproxy
    logging:
        driver: "json-file"
        options: 
            max-size: "10m"
            max-file: "10"
    hostname: mapproxy
    expose:
     - "8080"
     - "1717"
    volumes:
     - c:\code\themapcloud-mapproxy:/mapproxy/config
     - c:\temp\cache:/mapproxy/cache
    environment:
     - MAPPROXY_ENV=staging